"""empty message

Revision ID: 40a244ec2428
Revises: 
Create Date: 2018-01-04 11:15:33.913337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40a244ec2428'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('af_type',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('type_image_url', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_af_type_name'), 'af_type', ['name'], unique=True)
    op.create_table('af_user_profile',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('mobile', sa.String(length=11), nullable=False),
    sa.Column('avatar_url', sa.String(length=64), nullable=True),
    sa.Column('sex', sa.SmallInteger(), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('rank', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_af_user_profile_username'), 'af_user_profile', ['username'], unique=True)
    op.create_table('af_article',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('abstract', sa.String(length=100), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('collection_count', sa.Integer(), nullable=True),
    sa.Column('praise_count', sa.Integer(), nullable=True),
    sa.Column('main_text', sa.Text(), nullable=False),
    sa.Column('abs_image_url', sa.String(length=64), nullable=True),
    sa.Column('banner_image_url', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['af_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['af_user_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_af_article_title'), 'af_article', ['title'], unique=False)
    op.create_table('af_followers',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['af_user_profile.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['af_user_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('af_article_image_url',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['af_article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('af_article_praise',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('praise_user_id', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['af_article.id'], ),
    sa.ForeignKeyConstraint(['praise_user_id'], ['af_user_profile.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['af_user_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('af_comment',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('praise_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['af_article.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['af_user_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('af_index_banner',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('banner_image_url', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['af_article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('af_index_banner')
    op.drop_table('af_comment')
    op.drop_table('af_article_praise')
    op.drop_table('af_article_image_url')
    op.drop_table('af_followers')
    op.drop_index(op.f('ix_af_article_title'), table_name='af_article')
    op.drop_table('af_article')
    op.drop_index(op.f('ix_af_user_profile_username'), table_name='af_user_profile')
    op.drop_table('af_user_profile')
    op.drop_index(op.f('ix_af_type_name'), table_name='af_type')
    op.drop_table('af_type')
    # ### end Alembic commands ###
